### ISSUE TITLE
MAF Track Not Showing Up

### ISSUE THREAD

**Issue by ifreecell** [cmdcolin/mafviewer#8]
JBrowse version 1.12.1 

After installing the plugin, go to [test data](http://localhost/JBrowse/?data=plugins/MAFViewer/test/hg38), while the augustusGene track is shown, MAF track is not shown. 

![mafviewer](https://cloud.githubusercontent.com/assets/3411162/25949377/a23cc562-3657-11e7-95bf-6b56a1823502.png)

**Comment by cmdcolin** [comment]
You'll need to use 1.12.3,  because 1.12.1 didn't have bedtabix support

The MAFViewer relies on a derived bed tabix format

If you are unable to upgrade let me know and I can recommend workarounds

I'll update the readme to reflect (currently it mentions using jbrowse master but now 1.12.3 release is fine)
